// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagename

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
	"packagename/imports/models"
)

type MfaVerifyHandler interface {
	HandleMfaVerify(ctx context.Context, r packagenamemodels.MfaVerifyRequest) (*packagenamemodels.MfaVerifyResponse, error)
}
type Handler struct {
	validator    *validator.Validate
	mfaVerify    MfaVerifyHandler
	errorHandler ErrorHandler
}

func NewHandler(mfaVerify MfaVerifyHandler, opts ...Option) *Handler {
	h := &Handler{validator: validator.New(validator.WithRequiredStructEnabled()), mfaVerify: mfaVerify, errorHandler: DefaultErrorHandler}
	for _, opt := range opts {
		opt(h)
	}
	return h
}
func (h *Handler) AddRoutes(router chi.Router) {
}
func (h *Handler) AddMfaRoutes(router chi.Router) {
	router.Post("/auth/mfa/verify", h.handleMfaVerify)
}
func (h *Handler) parseMfaVerifyRequest(r *http.Request) (*packagenamemodels.MfaVerifyRequest, error) {
	return &packagenamemodels.MfaVerifyRequest{}, nil
}
func MfaVerify200() *packagenamemodels.MfaVerifyResponse {
	return &packagenamemodels.MfaVerifyResponse{StatusCode: 200, Response200: &packagenamemodels.MfaVerifyResponse200{}}
}
func (h *Handler) writeMfaVerify200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.MfaVerifyResponse200) {
}
func (h *Handler) writeMfaVerifyResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.MfaVerifyResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeMfaVerify200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleMfaVerifyRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseMfaVerifyRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.mfaVerify.HandleMfaVerify(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeMfaVerifyResponse(w, r, response)
	return
}
func (h *Handler) handleMfaVerify(w http.ResponseWriter, r *http.Request) {
	h.handleMfaVerifyRequest(w, r)
}

type ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string)
type Option func(*Handler)

func WithErrorHandler(eh ErrorHandler) Option {
	return func(h *Handler) {
		h.errorHandler = eh
	}
}
func (h *Handler) SetErrorHandler(eh ErrorHandler) {
	h.errorHandler = eh
}

var DefaultErrorHandler ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string) {
	http.Error(w, fmt.Sprintf("{\"error\":%s}", strconv.Quote(msg)), status)
}
