// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

import "packagename/generated/def/defmodels"

type OpRequestBody struct {
	ExternalRef *defmodels.ExternalRef `json:"external-ref,omitempty" validate:"omitempty"`
}
type OpRequest struct {
	Body OpRequestBody
}
type OpResponse200 struct {
}
type OpResponse struct {
	StatusCode  int
	Response200 *OpResponse200
}
