// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type PostExampleRequest struct {
	Body Body
}
type PostExampleResponse200 struct {
}
type PostExampleResponse struct {
	StatusCode  int
	Response200 *PostExampleResponse200
}
type Body struct {
	Message *string `json:"message,omitempty" validate:"omitempty"`
}
