// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type VerifyEmailByCodeRequest struct {
}
type VerifyEmailByCodeResponse200 struct {
}
type VerifyEmailByCodeResponse struct {
	StatusCode  int
	Response200 *VerifyEmailByCodeResponse200
}
type MfaVerifyRequest struct {
}
type MfaVerifyResponse200 struct {
}
type MfaVerifyResponse struct {
	StatusCode  int
	Response200 *MfaVerifyResponse200
}
type MfaChallengeRequest struct {
}
type MfaChallengeResponse200 struct {
}
type MfaChallengeResponse struct {
	StatusCode  int
	Response200 *MfaChallengeResponse200
}
type LoginRequest struct {
}
type LoginResponse200 struct {
}
type LoginResponse struct {
	StatusCode  int
	Response200 *LoginResponse200
}
