// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagename

import (
	"context"
	"encoding/json"
	"fmt"
	"mime"
	"net/http"
	"strconv"
	"github.com/go-chi/chi/v5"
	"github.com/go-faster/errors"
	"github.com/go-playground/validator/v10"
	"packagename/imports/models"
)

type GetExample2Handler interface {
	HandleGetExample2(ctx context.Context, r packagenamemodels.GetExample2Request) (*packagenamemodels.GetExample2Response, error)
}
type PostExampleParamNameHandler interface {
	HandlePostExampleParamName(ctx context.Context, r packagenamemodels.PostExampleParamNameRequest) (*packagenamemodels.PostExampleParamNameResponse, error)
}
type Handler struct {
	validator            *validator.Validate
	getExample2          GetExample2Handler
	postExampleParamName PostExampleParamNameHandler
	errorHandler         ErrorHandler
}

func NewHandler(getExample2 GetExample2Handler, postExampleParamName PostExampleParamNameHandler, opts ...Option) *Handler {
	h := &Handler{validator: validator.New(validator.WithRequiredStructEnabled()), getExample2: getExample2, postExampleParamName: postExampleParamName, errorHandler: DefaultErrorHandler}
	for _, opt := range opts {
		opt(h)
	}
	return h
}
func (h *Handler) AddRoutes(router chi.Router) {
	router.Get("/example2", h.handleGetExample2)
	router.Post("/example/{param_name}", h.handlePostExampleParamName)
}
func (h *Handler) parseGetExample2Request(r *http.Request) (*packagenamemodels.GetExample2Request, error) {
	return &packagenamemodels.GetExample2Request{}, nil
}
func GetExample2200() *packagenamemodels.GetExample2Response {
	return &packagenamemodels.GetExample2Response{StatusCode: 200, Response200: &packagenamemodels.GetExample2Response200{}}
}
func (h *Handler) writeGetExample2200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.GetExample2Response200) {
}
func (h *Handler) writeGetExample2Response(w http.ResponseWriter, r *http.Request, response *packagenamemodels.GetExample2Response) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeGetExample2200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
}
func (h *Handler) handleGetExample2Request(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseGetExample2Request(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.getExample2.HandleGetExample2(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
		return
	}
	h.writeGetExample2Response(w, r, response)
	return
}
func (h *Handler) handleGetExample2(w http.ResponseWriter, r *http.Request) {
	h.handleGetExample2Request(w, r)
}
func (h *Handler) parsePostExampleParamNamePathParams(r *http.Request) (*packagenamemodels.PostExampleParamNamePathParams, error) {
	var pathParams packagenamemodels.PostExampleParamNamePathParams
	paramName := chi.URLParam(r, "param_name")
	if paramName == "" {
		return nil, errors.New("param_name path param is required")
	}
	pathParams.ParamName = paramName
	err := h.validator.Struct(pathParams)
	if err != nil {
		return nil, err
	}
	return &pathParams, nil
}
func (h *Handler) parsePostExampleParamNameQueryParams(r *http.Request) (*packagenamemodels.PostExampleParamNameQueryParams, error) {
	var queryParams packagenamemodels.PostExampleParamNameQueryParams
	paramName2 := r.URL.Query().Get("param_name2")
	if paramName2 == "" {
		return nil, errors.New("param_name2 query param is required")
	}
	queryParams.ParamName2 = paramName2
	err := h.validator.Struct(queryParams)
	if err != nil {
		return nil, err
	}
	return &queryParams, nil
}
func (h *Handler) parsePostExampleParamNameHeaders(r *http.Request) (*packagenamemodels.PostExampleParamNameHeaders, error) {
	var headers packagenamemodels.PostExampleParamNameHeaders
	xHeader := r.Header.Get("X-Header")
	if xHeader == "" {
		return nil, errors.New("X-Header header is required")
	}
	headers.XHeader = xHeader
	err := h.validator.Struct(headers)
	if err != nil {
		return nil, err
	}
	return &headers, nil
}
func containsNull(data json.RawMessage) bool {
	var temp any
	err := json.Unmarshal(data, &temp)
	if err != nil {
		return false
	}
	return temp == nil
}
func ValidatePostExampleParamNameRequestBodyJSON(jsonData json.RawMessage) error {
	requiredFields := map[string]bool{"code": true}
	nullableFields := map[string]bool{}
	var obj map[string]json.RawMessage
	err := json.Unmarshal(jsonData, &obj)
	if err != nil {
		return err
	}
	var val json.RawMessage
	var exists bool
	for field := range requiredFields {
		val, exists = obj[field]
		if !exists {
			return errors.New("field " + field + " is required")
		}
		if !nullableFields[field] && containsNull(val) {
			return errors.New("field " + field + " cannot be null")
		}
	}
	return nil
}
func (h *Handler) parsePostExampleParamNameRequestBody(r *http.Request) (*packagenamemodels.PostExampleParamNameRequestBody, error) {
	var bodyJSON json.RawMessage
	err := json.NewDecoder(r.Body).Decode(&bodyJSON)
	if err != nil {
		return nil, err
	}
	err = ValidatePostExampleParamNameRequestBodyJSON(bodyJSON)
	if err != nil {
		return nil, err
	}
	var body packagenamemodels.PostExampleParamNameRequestBody
	err = json.Unmarshal(bodyJSON, &body)
	if err != nil {
		return nil, err
	}
	err = h.validator.Struct(body)
	if err != nil {
		return nil, err
	}
	return &body, nil
}
func (h *Handler) parsePostExampleParamNameRequest(r *http.Request) (*packagenamemodels.PostExampleParamNameRequest, error) {
	pathParams, err := h.parsePostExampleParamNamePathParams(r)
	if err != nil {
		return nil, err
	}
	queryParams, err := h.parsePostExampleParamNameQueryParams(r)
	if err != nil {
		return nil, err
	}
	headers, err := h.parsePostExampleParamNameHeaders(r)
	if err != nil {
		return nil, err
	}
	body, err := h.parsePostExampleParamNameRequestBody(r)
	if err != nil {
		return nil, err
	}
	return &packagenamemodels.PostExampleParamNameRequest{Path: *pathParams, Query: *queryParams, Headers: *headers, Body: *body}, nil
}
func PostExampleParamName200(headers packagenamemodels.PostExampleParamNameResponse200Headers) *packagenamemodels.PostExampleParamNameResponse {
	return &packagenamemodels.PostExampleParamNameResponse{StatusCode: 200, Response200: &packagenamemodels.PostExampleParamNameResponse200{Headers: headers}}
}
func (h *Handler) writePostExampleParamName200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.PostExampleParamNameResponse200) {
}
func (h *Handler) writePostExampleParamName200ResponseHeaders(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.PostExampleParamNameResponse200) {
	headersJSON, err := json.Marshal(resp.Headers)
	if err != nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
		return
	}
	var headers map[string]string
	err = json.Unmarshal(headersJSON, &headers)
	if err != nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
		return
	}
	for key, value := range headers {
		w.Header().Set(key, value)
	}
}
func (h *Handler) writePostExampleParamNameResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.PostExampleParamNameResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
			return
		}
		h.writePostExampleParamName200ResponseHeaders(w, r, response.Response200)
		w.WriteHeader(response.StatusCode)
		h.writePostExampleParamName200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
}
func (h *Handler) handlePostExampleParamNameRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parsePostExampleParamNameRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.postExampleParamName.HandlePostExampleParamName(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
		return
	}
	h.writePostExampleParamNameResponse(w, r, response)
	return
}
func (h *Handler) handlePostExampleParamName(w http.ResponseWriter, r *http.Request) {
	contentType, _, _ := mime.ParseMediaType(r.Header.Get("Content-Type"))
	switch contentType {
	case "application/json":
		h.handlePostExampleParamNameRequest(w, r)
		return
	case "":
		h.handlePostExampleParamNameRequest(w, r)
		return
	default:
		h.errorHandler(w, r, http.StatusUnsupportedMediaType, "Unsupported Content-Type")
		return
	}
}

type ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string)
type Option func(*Handler)

func WithErrorHandler(eh ErrorHandler) Option {
	return func(h *Handler) {
		h.errorHandler = eh
	}
}
func (h *Handler) SetErrorHandler(eh ErrorHandler) {
	h.errorHandler = eh
}

var DefaultErrorHandler ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string) {
	http.Error(w, fmt.Sprintf("{\"error\":%s}", strconv.Quote(msg)), status)
}
