// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagename

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"time"
	"github.com/go-chi/chi/v5"
	"github.com/go-faster/errors"
	"github.com/go-playground/validator/v10"
	"packagename/imports/models"
)

type OpHandler interface {
	HandleOp(ctx context.Context, r packagenamemodels.OpRequest) (*packagenamemodels.OpResponse, error)
}
type Handler struct {
	validator    *validator.Validate
	op           OpHandler
	errorHandler ErrorHandler
}

func NewHandler(op OpHandler, opts ...Option) *Handler {
	h := &Handler{validator: validator.New(validator.WithRequiredStructEnabled()), op: op, errorHandler: DefaultErrorHandler}
	for _, opt := range opts {
		opt(h)
	}
	return h
}
func (h *Handler) AddRoutes(router chi.Router) {
	router.Get("/example", h.handleOp)
}
func (h *Handler) parseOpQueryParams(r *http.Request) (*packagenamemodels.OpQueryParams, error) {
	var queryParams packagenamemodels.OpQueryParams
	from := r.URL.Query().Get("from")
	if from == "" {
		return nil, errors.New("from query param is required")
	}
	parsedFrom, err := time.Parse(time.RFC3339, from)
	if err != nil {
		return nil, errors.Wrap(err, "From is not a valid date-time format")
	}
	queryParams.From = parsedFrom
	to := r.URL.Query().Get("to")
	if to == "" {
		return nil, errors.New("to query param is required")
	}
	parsedTo, err := time.Parse(time.RFC3339, to)
	if err != nil {
		return nil, errors.Wrap(err, "To is not a valid date-time format")
	}
	queryParams.To = parsedTo
	err = h.validator.Struct(queryParams)
	if err != nil {
		return nil, err
	}
	return &queryParams, nil
}
func (h *Handler) parseOpHeaders(r *http.Request) (*packagenamemodels.OpHeaders, error) {
	var headers packagenamemodels.OpHeaders
	xSince := r.Header.Get("X-Since")
	if xSince == "" {
		return nil, errors.New("X-Since header is required")
	}
	parsedXSince, err := time.Parse(time.RFC3339, xSince)
	if err != nil {
		return nil, errors.Wrap(err, "XSince is not a valid date-time format")
	}
	headers.XSince = parsedXSince
	err = h.validator.Struct(headers)
	if err != nil {
		return nil, err
	}
	return &headers, nil
}
func (h *Handler) parseOpRequest(r *http.Request) (*packagenamemodels.OpRequest, error) {
	queryParams, err := h.parseOpQueryParams(r)
	if err != nil {
		return nil, err
	}
	headers, err := h.parseOpHeaders(r)
	if err != nil {
		return nil, err
	}
	return &packagenamemodels.OpRequest{Query: *queryParams, Headers: *headers}, nil
}
func Op200() *packagenamemodels.OpResponse {
	return &packagenamemodels.OpResponse{StatusCode: 200, Response200: &packagenamemodels.OpResponse200{}}
}
func (h *Handler) writeOp200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.OpResponse200) {
}
func (h *Handler) writeOpResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.OpResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeOp200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleOpRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseOpRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.op.HandleOp(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeOpResponse(w, r, response)
	return
}
func (h *Handler) handleOp(w http.ResponseWriter, r *http.Request) {
	h.handleOpRequest(w, r)
}

type ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string)
type Option func(*Handler)

func WithErrorHandler(eh ErrorHandler) Option {
	return func(h *Handler) {
		h.errorHandler = eh
	}
}
func (h *Handler) SetErrorHandler(eh ErrorHandler) {
	h.errorHandler = eh
}

var DefaultErrorHandler ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string) {
	http.Error(w, fmt.Sprintf("{\"error\":%s}", strconv.Quote(msg)), status)
}
