// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type OpQueryParams struct {
	Limit  int     `json:"limit" validate:"required,min=1,max=100"`
	Offset int64   `json:"offset" validate:"required"`
	Ratio  float64 `json:"ratio" validate:"required"`
	Page   *int32  `json:"page,omitempty" validate:"omitempty"`
}
type OpRequest struct {
	Query OpQueryParams
}
type OpResponse200 struct {
}
type OpResponse struct {
	StatusCode  int
	Response200 *OpResponse200
}
