// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagename

import (
	"context"
	"encoding/json"
	"fmt"
	"mime"
	"net/http"
	"strconv"
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
	"packagename/imports/models"
)

type PostExampleHandler interface {
	HandlePostExample(ctx context.Context, r packagenamemodels.PostExampleRequest) (*packagenamemodels.PostExampleResponse, error)
}
type Handler struct {
	validator    *validator.Validate
	postExample  PostExampleHandler
	errorHandler ErrorHandler
}

func NewHandler(postExample PostExampleHandler, opts ...Option) *Handler {
	h := &Handler{validator: validator.New(validator.WithRequiredStructEnabled()), postExample: postExample, errorHandler: DefaultErrorHandler}
	for _, opt := range opts {
		opt(h)
	}
	return h
}
func (h *Handler) AddRoutes(router chi.Router) {
	router.Post("/example", h.handlePostExample)
}
func (h *Handler) parsePostExampleRequestBody(r *http.Request) (*packagenamemodels.Body, error) {
	var bodyJSON json.RawMessage
	err := json.NewDecoder(r.Body).Decode(&bodyJSON)
	if err != nil {
		return nil, err
	}
	err = ValidateBodyJSON(bodyJSON)
	if err != nil {
		return nil, err
	}
	var body packagenamemodels.Body
	err = json.Unmarshal(bodyJSON, &body)
	if err != nil {
		return nil, err
	}
	err = h.validator.Struct(body)
	if err != nil {
		return nil, err
	}
	return &body, nil
}
func (h *Handler) parsePostExampleRequest(r *http.Request) (*packagenamemodels.PostExampleRequest, error) {
	body, err := h.parsePostExampleRequestBody(r)
	if err != nil {
		return nil, err
	}
	return &packagenamemodels.PostExampleRequest{Body: *body}, nil
}
func PostExample200() *packagenamemodels.PostExampleResponse {
	return &packagenamemodels.PostExampleResponse{StatusCode: 200, Response200: &packagenamemodels.PostExampleResponse200{}}
}
func (h *Handler) writePostExample200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.PostExampleResponse200) {
}
func (h *Handler) writePostExampleResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.PostExampleResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writePostExample200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
}
func (h *Handler) handlePostExampleRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parsePostExampleRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.postExample.HandlePostExample(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "InternalServerError")
		return
	}
	h.writePostExampleResponse(w, r, response)
	return
}
func (h *Handler) handlePostExample(w http.ResponseWriter, r *http.Request) {
	contentType, _, _ := mime.ParseMediaType(r.Header.Get("Content-Type"))
	switch contentType {
	case "application/json":
		h.handlePostExampleRequest(w, r)
		return
	case "":
		h.handlePostExampleRequest(w, r)
		return
	default:
		h.errorHandler(w, r, http.StatusUnsupportedMediaType, "Unsupported Content-Type")
		return
	}
}
func ValidateBodyJSON(_ json.RawMessage) error {
	return nil
}

type ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string)
type Option func(*Handler)

func WithErrorHandler(eh ErrorHandler) Option {
	return func(h *Handler) {
		h.errorHandler = eh
	}
}
func (h *Handler) SetErrorHandler(eh ErrorHandler) {
	h.errorHandler = eh
}

var DefaultErrorHandler ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string) {
	http.Error(w, fmt.Sprintf("{\"error\":%s}", strconv.Quote(msg)), status)
}
