// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type MfaVerifyRequest struct {
}
type MfaVerifyResponse200 struct {
}
type MfaVerifyResponse struct {
	StatusCode  int
	Response200 *MfaVerifyResponse200
}
