// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type GetExample2Request struct {
}
type GetExample2Response200 struct {
}
type GetExample2Response struct {
	StatusCode  int
	Response200 *GetExample2Response200
}
type PostExampleParamNamePathParams struct {
	ParamName string `json:"param_name" validate:"required"`
}
type PostExampleParamNameQueryParams struct {
	ParamName2 string `json:"param_name2" validate:"required"`
}
type PostExampleParamNameHeaders struct {
	XHeader string `json:"X-Header" validate:"required"`
}
type PostExampleParamNameRequestBody struct {
	Code string `json:"code"`
}
type PostExampleParamNameRequest struct {
	Path    PostExampleParamNamePathParams
	Query   PostExampleParamNameQueryParams
	Headers PostExampleParamNameHeaders
	Body    PostExampleParamNameRequestBody
}
type PostExampleParamNameResponse200Headers struct {
	XHeader string `json:"X-Header" validate:"required"`
}
type PostExampleParamNameResponse200 struct {
	Headers PostExampleParamNameResponse200Headers
}
type PostExampleParamNameResponse struct {
	StatusCode  int
	Response200 *PostExampleParamNameResponse200
}
