// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type OpCookies struct {
	CookieField *string `json:"cookie-field,omitempty" validate:"omitempty"`
}
type OpRequest struct {
	Cookies OpCookies
}
type OpResponse200 struct {
}
type OpResponse struct {
	StatusCode  int
	Response200 *OpResponse200
}
