// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagename

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"github.com/go-chi/chi/v5"
	"github.com/go-playground/validator/v10"
	"packagename/imports/models"
)

type VerifyEmailByCodeHandler interface {
	HandleVerifyEmailByCode(ctx context.Context, r packagenamemodels.VerifyEmailByCodeRequest) (*packagenamemodels.VerifyEmailByCodeResponse, error)
}
type MfaVerifyHandler interface {
	HandleMfaVerify(ctx context.Context, r packagenamemodels.MfaVerifyRequest) (*packagenamemodels.MfaVerifyResponse, error)
}
type MfaChallengeHandler interface {
	HandleMfaChallenge(ctx context.Context, r packagenamemodels.MfaChallengeRequest) (*packagenamemodels.MfaChallengeResponse, error)
}
type LoginHandler interface {
	HandleLogin(ctx context.Context, r packagenamemodels.LoginRequest) (*packagenamemodels.LoginResponse, error)
}
type Handler struct {
	validator         *validator.Validate
	verifyEmailByCode VerifyEmailByCodeHandler
	mfaVerify         MfaVerifyHandler
	mfaChallenge      MfaChallengeHandler
	login             LoginHandler
	errorHandler      ErrorHandler
}

func NewHandler(verifyEmailByCode VerifyEmailByCodeHandler, mfaVerify MfaVerifyHandler, mfaChallenge MfaChallengeHandler, login LoginHandler, opts ...Option) *Handler {
	h := &Handler{validator: validator.New(validator.WithRequiredStructEnabled()), verifyEmailByCode: verifyEmailByCode, mfaVerify: mfaVerify, mfaChallenge: mfaChallenge, login: login, errorHandler: DefaultErrorHandler}
	for _, opt := range opts {
		opt(h)
	}
	return h
}
func (h *Handler) AddRoutes(router chi.Router) {
	router.Post("/auth/login", h.handleLogin)
}
func (h *Handler) AddVerifyEmailRoutes(router chi.Router) {
	router.Post("/me/email/verify-by-code", h.handleVerifyEmailByCode)
}
func (h *Handler) AddMfaRoutes(router chi.Router) {
	router.Post("/auth/mfa/verify", h.handleMfaVerify)
	router.Post("/auth/mfa/challenge", h.handleMfaChallenge)
}
func (h *Handler) parseVerifyEmailByCodeRequest(r *http.Request) (*packagenamemodels.VerifyEmailByCodeRequest, error) {
	return &packagenamemodels.VerifyEmailByCodeRequest{}, nil
}
func VerifyEmailByCode200() *packagenamemodels.VerifyEmailByCodeResponse {
	return &packagenamemodels.VerifyEmailByCodeResponse{StatusCode: 200, Response200: &packagenamemodels.VerifyEmailByCodeResponse200{}}
}
func (h *Handler) writeVerifyEmailByCode200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.VerifyEmailByCodeResponse200) {
}
func (h *Handler) writeVerifyEmailByCodeResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.VerifyEmailByCodeResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeVerifyEmailByCode200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleVerifyEmailByCodeRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseVerifyEmailByCodeRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.verifyEmailByCode.HandleVerifyEmailByCode(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeVerifyEmailByCodeResponse(w, r, response)
	return
}
func (h *Handler) handleVerifyEmailByCode(w http.ResponseWriter, r *http.Request) {
	h.handleVerifyEmailByCodeRequest(w, r)
}
func (h *Handler) parseMfaVerifyRequest(r *http.Request) (*packagenamemodels.MfaVerifyRequest, error) {
	return &packagenamemodels.MfaVerifyRequest{}, nil
}
func MfaVerify200() *packagenamemodels.MfaVerifyResponse {
	return &packagenamemodels.MfaVerifyResponse{StatusCode: 200, Response200: &packagenamemodels.MfaVerifyResponse200{}}
}
func (h *Handler) writeMfaVerify200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.MfaVerifyResponse200) {
}
func (h *Handler) writeMfaVerifyResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.MfaVerifyResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeMfaVerify200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleMfaVerifyRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseMfaVerifyRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.mfaVerify.HandleMfaVerify(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeMfaVerifyResponse(w, r, response)
	return
}
func (h *Handler) handleMfaVerify(w http.ResponseWriter, r *http.Request) {
	h.handleMfaVerifyRequest(w, r)
}
func (h *Handler) parseMfaChallengeRequest(r *http.Request) (*packagenamemodels.MfaChallengeRequest, error) {
	return &packagenamemodels.MfaChallengeRequest{}, nil
}
func MfaChallenge200() *packagenamemodels.MfaChallengeResponse {
	return &packagenamemodels.MfaChallengeResponse{StatusCode: 200, Response200: &packagenamemodels.MfaChallengeResponse200{}}
}
func (h *Handler) writeMfaChallenge200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.MfaChallengeResponse200) {
}
func (h *Handler) writeMfaChallengeResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.MfaChallengeResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeMfaChallenge200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleMfaChallengeRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseMfaChallengeRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.mfaChallenge.HandleMfaChallenge(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeMfaChallengeResponse(w, r, response)
	return
}
func (h *Handler) handleMfaChallenge(w http.ResponseWriter, r *http.Request) {
	h.handleMfaChallengeRequest(w, r)
}
func (h *Handler) parseLoginRequest(r *http.Request) (*packagenamemodels.LoginRequest, error) {
	return &packagenamemodels.LoginRequest{}, nil
}
func Login200() *packagenamemodels.LoginResponse {
	return &packagenamemodels.LoginResponse{StatusCode: 200, Response200: &packagenamemodels.LoginResponse200{}}
}
func (h *Handler) writeLogin200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.LoginResponse200) {
}
func (h *Handler) writeLoginResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.LoginResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeLogin200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleLoginRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseLoginRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.login.HandleLogin(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeLoginResponse(w, r, response)
	return
}
func (h *Handler) handleLogin(w http.ResponseWriter, r *http.Request) {
	h.handleLoginRequest(w, r)
}

type ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string)
type Option func(*Handler)

func WithErrorHandler(eh ErrorHandler) Option {
	return func(h *Handler) {
		h.errorHandler = eh
	}
}
func (h *Handler) SetErrorHandler(eh ErrorHandler) {
	h.errorHandler = eh
}

var DefaultErrorHandler ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string) {
	http.Error(w, fmt.Sprintf("{\"error\":%s}", strconv.Quote(msg)), status)
}
