// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagename

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"github.com/go-chi/chi/v5"
	"github.com/go-faster/errors"
	"github.com/go-playground/validator/v10"
	"packagename/imports/models"
)

type OpHandler interface {
	HandleOp(ctx context.Context, r packagenamemodels.OpRequest) (*packagenamemodels.OpResponse, error)
}
type Handler struct {
	validator    *validator.Validate
	op           OpHandler
	errorHandler ErrorHandler
}

func NewHandler(op OpHandler, opts ...Option) *Handler {
	h := &Handler{validator: validator.New(validator.WithRequiredStructEnabled()), op: op, errorHandler: DefaultErrorHandler}
	for _, opt := range opts {
		opt(h)
	}
	return h
}
func (h *Handler) AddRoutes(router chi.Router) {
	router.Get("/example", h.handleOp)
}
func (h *Handler) parseOpQueryParams(r *http.Request) (*packagenamemodels.OpQueryParams, error) {
	var queryParams packagenamemodels.OpQueryParams
	limit := r.URL.Query().Get("limit")
	if limit == "" {
		return nil, errors.New("limit query param is required")
	}
	parsedLimit, err := strconv.Atoi(limit)
	if err != nil {
		return nil, errors.Wrap(err, "Limit is not a valid integer")
	}
	queryParams.Limit = parsedLimit
	offset := r.URL.Query().Get("offset")
	if offset == "" {
		return nil, errors.New("offset query param is required")
	}
	parsedOffset, err := strconv.ParseInt(offset, 10, 64)
	if err != nil {
		return nil, errors.Wrap(err, "Offset is not a valid integer")
	}
	queryParams.Offset = parsedOffset
	ratio := r.URL.Query().Get("ratio")
	if ratio == "" {
		return nil, errors.New("ratio query param is required")
	}
	parsedRatio, err := strconv.ParseFloat(ratio, 64)
	if err != nil {
		return nil, errors.Wrap(err, "Ratio is not a valid number")
	}
	queryParams.Ratio = parsedRatio
	page := r.URL.Query().Get("page")
	if page != "" {
		parsedPage, err := strconv.ParseInt(page, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, "Page is not a valid integer")
		}
		convertedPage := int32(parsedPage)
		queryParams.Page = &convertedPage
	}
	err = h.validator.Struct(queryParams)
	if err != nil {
		return nil, err
	}
	return &queryParams, nil
}
func (h *Handler) parseOpRequest(r *http.Request) (*packagenamemodels.OpRequest, error) {
	queryParams, err := h.parseOpQueryParams(r)
	if err != nil {
		return nil, err
	}
	return &packagenamemodels.OpRequest{Query: *queryParams}, nil
}
func Op200() *packagenamemodels.OpResponse {
	return &packagenamemodels.OpResponse{StatusCode: 200, Response200: &packagenamemodels.OpResponse200{}}
}
func (h *Handler) writeOp200Response(w http.ResponseWriter, r *http.Request, resp *packagenamemodels.OpResponse200) {
}
func (h *Handler) writeOpResponse(w http.ResponseWriter, r *http.Request, response *packagenamemodels.OpResponse) {
	switch response.StatusCode {
	case 200:
		if response.Response200 == nil {
			h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
			return
		}
		w.WriteHeader(response.StatusCode)
		h.writeOp200Response(w, r, response.Response200)
		return
	}
	h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
}
func (h *Handler) handleOpRequest(w http.ResponseWriter, r *http.Request) {
	request, err := h.parseOpRequest(r)
	if err != nil {
		h.errorHandler(w, r, http.StatusBadRequest, err.Error())
		return
	}
	ctx := r.Context()
	response, err := h.op.HandleOp(ctx, *request)
	if err != nil || response == nil {
		h.errorHandler(w, r, http.StatusInternalServerError, "Internal Server Error")
		return
	}
	h.writeOpResponse(w, r, response)
	return
}
func (h *Handler) handleOp(w http.ResponseWriter, r *http.Request) {
	h.handleOpRequest(w, r)
}

type ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string)
type Option func(*Handler)

func WithErrorHandler(eh ErrorHandler) Option {
	return func(h *Handler) {
		h.errorHandler = eh
	}
}
func (h *Handler) SetErrorHandler(eh ErrorHandler) {
	h.errorHandler = eh
}

var DefaultErrorHandler ErrorHandler = func(w http.ResponseWriter, r *http.Request, status int, msg string) {
	http.Error(w, fmt.Sprintf("{\"error\":%s}", strconv.Quote(msg)), status)
}
