// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type OpRequest struct {
	Body Body
}
type OpResponse200 struct {
}
type OpResponse struct {
	StatusCode  int
	Response200 *OpResponse200
}
type Body struct {
	Message *string `json:"message,omitempty" validate:"omitempty"`
}
