// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

import "time"

type OpQueryParams struct {
	From time.Time `json:"from" validate:"required"`
	To   time.Time `json:"to" validate:"required"`
}
type OpHeaders struct {
	XSince time.Time `json:"X-Since" validate:"required"`
}
type OpRequest struct {
	Query   OpQueryParams
	Headers OpHeaders
}
type OpResponse200 struct {
}
type OpResponse struct {
	StatusCode  int
	Response200 *OpResponse200
}
