package generator_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/sebdah/goldie/v2"
	"github.com/sintoniastrategy/validgo-gen/internal/generator"
	"github.com/sintoniastrategy/validgo-gen/internal/generator/options"
	"github.com/stretchr/testify/assert"
)

func TestGenerateValidInput(t *testing.T) {
	mockInput := `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ExampleModel:
      type: object
      properties:
        field_two:
          type: integer
        field_one:
          type: string
          minLength: 3
          maxLength: 10
        field_three:
          $ref: '#/components/schemas/StringModel'
        field4:
          type: object
          properties:
            field1:
              type: string
        field5:
          $ref: '#/components/schemas/ObjectModel'
        field6:
          type: number
          minimum: 1.5
          maximum: 10.5
      required:
        - field_one
        - field6
    StringModel:
      type: string
    IntModel:
      type: integer
    ObjectModel:
      type: object
      properties:
        field1:
          type: string
`

	expectedOutput := `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ExampleModelField4 struct {
	Field1 *string ` + "`json:\"field1,omitempty\" validate:\"omitempty\"`" + `
}
type ExampleModel struct {
	Field4     *ExampleModelField4 ` + "`json:\"field4,omitempty\" validate:\"omitempty\"`" + `
	Field5     *ObjectModel        ` + "`json:\"field5,omitempty\" validate:\"omitempty\"`" + `
	Field6     float64             ` + "`json:\"field6\" validate:\"min=1.5,max=10.5\"`" + `
	FieldOne   string              ` + "`json:\"field_one\" validate:\"min=3,max=10\"`" + `
	FieldThree *StringModel        ` + "`json:\"field_three,omitempty\" validate:\"omitempty\"`" + `
	FieldTwo   *int                ` + "`json:\"field_two,omitempty\" validate:\"omitempty\"`" + `
}
type IntModel int
type ObjectModel struct {
	Field1 *string ` + "`json:\"field1,omitempty\" validate:\"omitempty\"`" + `
}
type StringModel string
`

	input := strings.NewReader(mockInput)
	outputModels := &bytes.Buffer{}
	outputHandlers := &bytes.Buffer{}
	gen := generator.NewGenerator(&options.Options{
		PackagePrefix: "packagename",
	})
	gen.PackageName = "packagename"
	gen.ImportPrefix = "imports"
	gen.ModelsImportPath = "packagename/imports/models"
	err := gen.PrepareAndRead(input)
	assert.NoError(t, err)
	err = gen.GenerateFiles()
	assert.NoError(t, err)
	err = gen.WriteToOutput(outputModels, outputHandlers)
	assert.NoError(t, err)

	assert.Equal(t, expectedOutput, outputModels.String())
}

func TestGeneratorFeatures(t *testing.T) {
	for _, tc := range []struct {
		name     string
		input    string
		expected string
	}{
		{
			name: "TestString",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    StringModel:
      type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type StringModel string
`,
		},
		{
			name: "TestInt",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    IntModel:
      type: integer
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type IntModel int
`,
		},
		{
			name: "TestNumber",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    NumberModel:
      type: number
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type NumberModel float64
`,
		},
		{
			name: "TestBool",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    BoolModel:
      type: boolean
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type BoolModel bool
`,
		},
		{
			name: "TestSimpleObject",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        string_field:
          type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModel struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
`,
		},
		{
			name: "TestEmptyObject",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModel struct {
}
`,
		},
		{
			name: "TestStringValidatorsObject",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        string_field:
          type: string
          minLength: 3
          maxLength: 10
          format: email
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModel struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty,min=3,max=10,email\"`" + `
}
`,
		},
		{
			name: "TestStringReferenceObject",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    StringModel:
      type: string
      minLength: 3
      maxLength: 10
    ObjectModel:
      type: object
      properties:
        string_field:
          $ref: '#/components/schemas/StringModel'
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModel struct {
	StringField *StringModel ` + "`json:\"string_field,omitempty\" validate:\"omitempty,min=3,max=10\"`" + `
}
type StringModel string
`,
		},
		{
			name: "TestFieldTypesInObject",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        string_field:
          type: string
        int_field:
          type: integer
        number_field:
          type: number
        bool_field:
          type: boolean
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModel struct {
	BoolField   *bool    ` + "`json:\"bool_field,omitempty\" validate:\"omitempty\"`" + `
	IntField    *int     ` + "`json:\"int_field,omitempty\" validate:\"omitempty\"`" + `
	NumberField *float64 ` + "`json:\"number_field,omitempty\" validate:\"omitempty\"`" + `
	StringField *string  ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
`,
		},
		{
			name: "TestObjectRef",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        object_field:
          $ref: '#/components/schemas/Object2Model'
    Object2Model:
      type: object
      properties:
        string_field:
          type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type Object2Model struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
type ObjectModel struct {
	ObjectField *Object2Model ` + "`json:\"object_field,omitempty\" validate:\"omitempty\"`" + `
}
`,
		},
		{
			name: "TestNestedObject",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        object_field:
          type: object
          properties:
            string_field:
              type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModelObjectField struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
type ObjectModel struct {
	ObjectField *ObjectModelObjectField ` + "`json:\"object_field,omitempty\" validate:\"omitempty\"`" + `
}
`,
		},
		{
			name: "TestArrayStringRefSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        $ref: '#/components/schemas/StringModel'
    StringModel:
      type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []StringModel
type StringModel string
`,
		},
		{
			name: "TestArrayObjectRefSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        $ref: '#/components/schemas/ObjectModel'
    ObjectModel:
      type: object
      properties:
        string_field:
          type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []ObjectModel
type ObjectModel struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
`,
		},
		{
			name: "TestArrayStringSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []string
`,
		},
		{
			name: "TestArrayBoolSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: boolean
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []bool
`,
		},
		{
			name: "TestArrayIntSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: integer
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []int
`,
		},
		{
			name: "TestArrayNumberSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: number
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []float64
`,
		},
		{
			name: "TestArrayObjectSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: object
        properties:
          string_field:
            type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModelItem struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
type ArrayModel []ArrayModelItem
`,
		},
		{
			name: "TestArrayNestedObjectSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: object
        properties:
          object_field:
            type: object
            properties:
              string_field:
                type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModelItemObjectField struct {
	StringField *string ` + "`json:\"string_field,omitempty\" validate:\"omitempty\"`" + `
}
type ArrayModelItem struct {
	ObjectField *ArrayModelItemObjectField ` + "`json:\"object_field,omitempty\" validate:\"omitempty\"`" + `
}
type ArrayModel []ArrayModelItem
`,
		},
		{
			name: "TestArrayNestedArrayRefSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        $ref: '#/components/schemas/Array2Model'
    Array2Model:
      type: array
      items:
        type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type Array2Model []string
type ArrayModel []Array2Model
`,
		},
		{
			name: "TestArrayNestedArraySchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: array
        items:
          type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModelItem []string
type ArrayModel []ArrayModelItem
`,
		},
		{
			name: "TestObjectRefArraySchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ArrayModel:
      type: array
      items:
        type: string
    ObjectModel:
      type: object
      properties:
        array_field:
          $ref: '#/components/schemas/ArrayModel'
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ArrayModel []string
type ObjectModel struct {
	ArrayField *ArrayModel ` + "`json:\"array_field,omitempty\" validate:\"omitempty,dive\"`" + `
}
`,
		},
		{
			name: "TestObjectArraySchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        array_field:
          type: array
          items:
            type: string
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModelArrayField []string
type ObjectModel struct {
	ArrayField *ObjectModelArrayField ` + "`json:\"array_field,omitempty\" validate:\"omitempty,dive\"`" + `
}
`,
		},
		{
			name: "TestObjectArrayValidatorsSchema",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths: {}
components:
  schemas:
    ObjectModel:
      type: object
      properties:
        array_field:
          type: array
          minItems: 1
          maxItems: 10
          uniqueItems: true
          items:
            type: string
            minLength: 3
            maxLength: 10
`,
			expected: `// Code generated by github.com/sintoniastrategy/validgo-gen; DO NOT EDIT.

package packagenamemodels

type ObjectModelArrayField []string
type ObjectModel struct {
	ArrayField *ObjectModelArrayField ` + "`json:\"array_field,omitempty\" validate:\"omitempty,min=1,max=10,unique,dive,min=3,max=10\"`" + `
}
`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := strings.NewReader(tc.input)
			outputModels := &bytes.Buffer{}
			outputHandlers := &bytes.Buffer{}
			gen := generator.NewGenerator(&options.Options{
				PackagePrefix: "packagename",
			})
			gen.PackageName = "packagename"
			gen.ImportPrefix = "imports"
			gen.ModelsImportPath = "packagename/imports/models"
			err := gen.PrepareAndRead(input)
			assert.NoError(t, err)
			err = gen.GenerateFiles()
			assert.NoError(t, err)
			err = gen.WriteToOutput(outputModels, outputHandlers)
			assert.NoError(t, err)

			assert.Equal(t, tc.expected, outputModels.String())
		})
	}
}

func TestGeneratePaths(t *testing.T) {
	for _, tc := range []struct {
		name  string
		input string
	}{
		{
			name: "TestString",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example/{param_name}:
    post:
      summary: Example
      parameters:
        - name: param_name
          in: path
          required: true
          schema:
            type: string
        - name: param_name2
          in: query
          required: true
          schema:
            type: string
        - name: X-Header
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
                - code
      responses:
        '200':
          description: OK
          headers:
            X-Header:
              description: X-Header
              schema:
                type: string
              required: true
  /example2:
    get:
      summary: Example
      responses:
        '200':
          description: OK
`,
		},
		{
			name: "TestRequiredDateTimeParams",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example:
    get:
      operationId: op
      summary: Example
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: X-Since
          in: header
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
`,
		},
		{
			name: "TestNumericParams",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example:
    get:
      operationId: op
      summary: Example
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - name: offset
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: ratio
          in: query
          required: true
          schema:
            type: number
        - name: page
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := strings.NewReader(tc.input)
			outputModels := &bytes.Buffer{}
			outputHandlers := &bytes.Buffer{}
			gen := generator.NewGenerator(&options.Options{
				PackagePrefix: "packagename",
			})
			gen.PackageName = "packagename"
			gen.ImportPrefix = "imports"
			gen.ModelsImportPath = "packagename/imports/models"
			err := gen.PrepareAndRead(input)
			assert.NoError(t, err)
			err = gen.GenerateFiles()
			assert.NoError(t, err)
			err = gen.WriteToOutput(outputModels, outputHandlers)
			assert.NoError(t, err)

			g := goldie.New(t,
				goldie.WithFixtureDir("testdata/golden"),
				goldie.WithNameSuffix(""),
			)
			caseName := strings.ReplaceAll(t.Name(), "/", "_")
			g.Assert(t, caseName+"_models.go", outputModels.Bytes())
			g.Assert(t, caseName+"_handlers.go", outputHandlers.Bytes())
		})
	}
}

func TestGenerateFeatures(t *testing.T) {
	for _, tc := range []struct {
		name  string
		input string
	}{
		{
			name: "body ref",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example:
    post:
      summary: Example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body'
      responses:
        '200':
          description: OK
components:
  schemas:
    Body:
      type: object
      properties:
        message:
          type: string
`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := strings.NewReader(tc.input)
			outputModels := &bytes.Buffer{}
			outputHandlers := &bytes.Buffer{}
			gen := generator.NewGenerator(&options.Options{
				PackagePrefix: "packagename",
			})
			gen.PackageName = "packagename"
			gen.ImportPrefix = "imports"
			gen.ModelsImportPath = "packagename/imports/models"
			err := gen.PrepareAndRead(input)
			assert.NoError(t, err)
			err = gen.GenerateFiles()
			assert.NoError(t, err)
			err = gen.WriteToOutput(outputModels, outputHandlers)
			assert.NoError(t, err)

			g := goldie.New(t,
				goldie.WithFixtureDir("testdata/golden"),
				goldie.WithNameSuffix(""),
			)
			caseName := strings.ReplaceAll(t.Name(), "/", "_")
			g.Assert(t, caseName+"_models.go", outputModels.Bytes())
			g.Assert(t, caseName+"_handlers.go", outputHandlers.Bytes())
		})
	}
}

func TestGenerateFeatures2(t *testing.T) {
	for _, tc := range []struct {
		name  string
		input string
	}{
		{
			name: "operation id",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example:
    post:
      operationId: op
      summary: Example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body'
      responses:
        '200':
          description: OK
components:
  schemas:
    Body:
      type: object
      properties:
        message:
          type: string
`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := strings.NewReader(tc.input)
			outputModels := &bytes.Buffer{}
			outputHandlers := &bytes.Buffer{}
			gen := generator.NewGenerator(&options.Options{
				PackagePrefix: "packagename",
			})
			gen.PackageName = "packagename"
			gen.ImportPrefix = "imports"
			gen.ModelsImportPath = "packagename/imports/models"
			err := gen.PrepareAndRead(input)
			assert.NoError(t, err)
			err = gen.GenerateFiles()
			assert.NoError(t, err)
			err = gen.WriteToOutput(outputModels, outputHandlers)
			assert.NoError(t, err)

			g := goldie.New(t,
				goldie.WithFixtureDir("testdata/golden"),
				goldie.WithNameSuffix(""),
			)
			caseName := strings.ReplaceAll(t.Name(), "/", "_")
			g.Assert(t, caseName+"_models.go", outputModels.Bytes())
			g.Assert(t, caseName+"_handlers.go", outputHandlers.Bytes())
		})
	}
}

func TestGenerateCookies(t *testing.T) {
	for _, tc := range []struct {
		name  string
		input string
	}{
		{
			name: "operation id",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example:
    post:
      operationId: op
      summary: Example
      parameters:
        - name: cookie-field
          in: cookie
          schema:
            type: string
      responses:
        '200':
          description: OK
`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := strings.NewReader(tc.input)
			outputModels := &bytes.Buffer{}
			outputHandlers := &bytes.Buffer{}
			gen := generator.NewGenerator(&options.Options{
				PackagePrefix: "packagename",
			})
			gen.PackageName = "packagename"
			gen.ImportPrefix = "imports"
			gen.ModelsImportPath = "packagename/imports/models"
			err := gen.PrepareAndRead(input)
			assert.NoError(t, err)
			err = gen.GenerateFiles()
			assert.NoError(t, err)
			err = gen.WriteToOutput(outputModels, outputHandlers)
			assert.NoError(t, err)

			g := goldie.New(t,
				goldie.WithFixtureDir("testdata/golden"),
				goldie.WithNameSuffix(""),
			)
			caseName := strings.ReplaceAll(t.Name(), "/", "_")
			g.Assert(t, caseName+"_models.go", outputModels.Bytes())
			g.Assert(t, caseName+"_handlers.go", outputHandlers.Bytes())
		})
	}
}

func TestGenerateExternal(t *testing.T) {
	for _, tc := range []struct {
		name  string
		input string
	}{
		{
			name: "operation id",
			input: `openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /example:
    post:
      operationId: op
      summary: Example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                external-ref:
                  $ref: 'testdata/def.yml#/components/schemas/ExternalRef'
      responses:
        '200':
          description: OK
`,
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			input := strings.NewReader(tc.input)
			outputModels := &bytes.Buffer{}
			outputHandlers := &bytes.Buffer{}
			gen := generator.NewGenerator(&options.Options{
				PackagePrefix: "packagename",
			})
			gen.PackageName = "packagename"
			gen.ImportPrefix = "imports"
			gen.ModelsImportPath = "packagename/imports/models"
			err := gen.PrepareAndRead(input)
			assert.NoError(t, err)
			err = gen.GenerateFiles()
			assert.NoError(t, err)
			err = gen.WriteToOutput(outputModels, outputHandlers)
			assert.NoError(t, err)

			g := goldie.New(t,
				goldie.WithFixtureDir("testdata/golden"),
				goldie.WithNameSuffix(""),
			)
			caseName := strings.ReplaceAll(t.Name(), "/", "_")
			g.Assert(t, caseName+"_models.go", outputModels.Bytes())
			g.Assert(t, caseName+"_handlers.go", outputHandlers.Bytes())
		})
	}
}
